# Generated by Django 4.1.7 on 2023-05-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_currency_user_curreny_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
