# Generated by Django 4.1.7 on 2023-05-13 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_email_alter_user_is_host"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="curreny",
            new_name="currency",
        ),
    ]
